apiVersion: v1
kind: Service
metadata:
   name: frontend-service
   namespace: default
   labels:
     app: frontend
      
spec:
   type: NodePort
   ports:
     - protocol: TCP
       port: 80
       targetPort: 80
       nodePort: 32001 
   selector:
     app: frontend